#!/usr/bin/env python3
"""
Toffee TV Cookie Scraper - All-in-One Solution
GitHub Actions-এ run করার জন্য সম্পূর্ণ প্যাকেজ
"""

import asyncio
import json
import logging
import os
import sys
import time
from datetime import datetime
from typing import List, Dict, Optional

# ==================== CONFIGURATION ====================
CONFIG = {
    "BASE_URL": "https://toffeelive.com/",
    "VIDEO_URL": "https://toffeelive.com/en/watch/DNMXs5UBm1RY_In7IJ72",
    "HEADLESS": True,
    "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "IMPORTANT_KEYWORDS": ['Edge-Cache', 'token', 'session', 'auth', 'cf_', '__cf'],
    "PAGE_LOAD_WAIT": 10,
    "VIDEO_LOAD_WAIT": 15,
    "OUTPUT_FILE": "toffee_cookies.json"
}

# ==================== LOGGING SETUP ====================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger(__name__)

# ==================== COOKIE UTILITIES ====================
def load_cookies_from_file(filename: str = "toffee_cookies.json") -> List[Dict]:
    """JSON ফাইল থেকে Cookie লোড করে"""
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data.get('all_cookies', [])
    except FileNotFoundError:
        logger.warning(f"File '{filename}' not found")
        return []
    except json.JSONDecodeError:
        logger.error(f"Invalid JSON in '{filename}'")
        return []

def get_cookie_value(cookies: List[Dict], cookie_name: str) -> Optional[str]:
    """নির্দিষ্ট নামের Cookie-র মান বের করে"""
    for cookie in cookies:
        if cookie.get('name') == cookie_name:
            return cookie.get('value')
    return None

def format_cookies_for_curl(cookies: List[Dict]) -> str:
    """cURL কমান্ডের জন্য Cookie ফরম্যাট করে"""
    cookie_strings = []
    for cookie in cookies:
        cookie_strings.append(f"{cookie['name']}={cookie['value']}")
    return "; ".join(cookie_strings)

def check_cookie_expiry(cookie: Dict) -> str:
    """Cookie-র মেয়াদ চেক করে"""
    expires = cookie.get('expires')
    if not expires or expires == -1:
        return "Session cookie"
    try:
        current_time = int(time.time())
        days_left = (int(expires) - current_time) // 86400
        if days_left > 0:
            return f"Expires in {days_left} days"
        else:
            hours_left = (int(expires) - current_time) // 3600
            return f"Expires in {hours_left} hours" if hours_left > 0 else "Expired"
    except:
        return "Invalid expiry format"

def save_cookies_as_netscape(cookies: List[Dict], filename: str = "cookies.txt"):
    """Netscape ফরম্যাটে Cookie সেভ (wget/curl এর জন্য)"""
    with open(filename, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
        f.write("# This file was generated by Toffee Cookie Scraper\n\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '')
            flag = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            expires = str(cookie.get('expires', 0))
            name = cookie['name']
            value = cookie['value']
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
    
    logger.info(f"✅ Cookies saved in Netscape format: {filename}")

# ==================== MAIN SCRAPER ====================
async def scrape_toffee_cookies():
    """
    Toffee TV থেকে Cookie সংগ্রহ করে JSON ফাইলে সেভ করে
    """
    logger.info("🚀 Starting Toffee TV Cookie Scraper...")
    logger.info(f"🐍 Python version: {sys.version}")
    
    # Playwright ইম্পোর্ট (শুধুমাত্র এখানে)
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        logger.error("❌ Playwright not installed! Run: pip install playwright && playwright install chromium")
        return None
    
    async with async_playwright() as p:
        # ব্রাউজার লঞ্চ - GitHub-এর জন্য অপটিমাইজড
        browser = await p.chromium.launch(
            headless=CONFIG["HEADLESS"],
            args=[
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-accelerated-2d-canvas',
                '--disable-gpu',
                '--window-size=1920,1080'
            ]
        )
        context = await browser.new_context(
            user_agent=CONFIG["USER_AGENT"],
            viewport={'width': 1920, 'height': 1080}
        )
        page = await context.new_page()

        try:
            # স্টেপ ১: হোমপেজ ভিজিট
            logger.info(f"🌐 Navigating to: {CONFIG['BASE_URL']}")
            await page.goto(CONFIG['BASE_URL'], wait_until="domcontentloaded", timeout=30000)
            await page.wait_for_timeout(CONFIG['PAGE_LOAD_WAIT'] * 1000)

            # স্টেপ ২: কুকি কনসেন্ট
            try:
                accept_buttons = await page.query_selector_all(
                    'button:has-text("Accept"), button:has-text("Accept All"), button:has-text("OK")'
                )
                if accept_buttons:
                    await accept_buttons[0].click()
                    logger.info("✅ Accepted cookies")
                    await page.wait_for_timeout(2000)
                else:
                    logger.info("ℹ️ No cookie consent button found")
            except Exception as e:
                logger.info(f"ℹ️ Cookie consent handling skipped: {str(e)}")

            # স্টেপ ৩: ভিডিও পেজে যান
            logger.info(f"📺 Loading video page: {CONFIG['VIDEO_URL']}")
            await page.goto(CONFIG['VIDEO_URL'], wait_until="domcontentloaded", timeout=30000)
            await page.wait_for_timeout(CONFIG['VIDEO_LOAD_WAIT'] * 1000)

            # স্টেপ ৪: পেজের স্ক্রিনশট নিন (ডিবাগের জন্য)
            screenshot_path = "page_screenshot.png"
            await page.screenshot(path=screenshot_path)
            logger.info(f"📸 Screenshot saved: {screenshot_path}")

            # স্টেপ ৫: সব Cookie সংগ্রহ
            all_cookies = await context.cookies()
            logger.info(f"🍪 Total cookies collected: {len(all_cookies)}")

            # কুকির বিস্তারিত তথ্য
            cookie_details = []
            for cookie in all_cookies:
                cookie_info = {
                    'name': cookie['name'],
                    'value': cookie['value'],
                    'domain': cookie.get('domain', ''),
                    'path': cookie.get('path', '/'),
                    'expires': cookie.get('expires', 'Session'),
                    'secure': cookie.get('secure', False),
                    'httpOnly': cookie.get('httpOnly', False),
                    'sameSite': cookie.get('sameSite', 'None')
                }
                cookie_details.append(cookie_info)

            # গুরুত্বপূর্ণ Cookie ফিল্টার
            important_cookies = []
            for cookie in all_cookies:
                if any(keyword in cookie['name'] for keyword in CONFIG['IMPORTANT_KEYWORDS']):
                    important_cookies.append(cookie)

            logger.info(f"⭐ Important cookies found: {len(important_cookies)}")

            # JSON ফরম্যাটে সেভ
            cookie_data = {
                "scraped_at": datetime.now().isoformat(),
                "url": CONFIG['VIDEO_URL'],
                "total_cookies": len(all_cookies),
                "important_count": len(important_cookies),
                "important_cookies": important_cookies,
                "all_cookies": cookie_details,
                "summary": {
                    "edge_cache_cookie": next((c for c in all_cookies if "Edge-Cache" in c['name']), None),
                    "session_cookie": next((c for c in all_cookies if "session" in c['name'].lower()), None),
                    "auth_cookie": next((c for c in all_cookies if "auth" in c['name'].lower()), None)
                }
            }

            with open(CONFIG['OUTPUT_FILE'], "w", encoding='utf-8') as f:
                json.dump(cookie_data, f, indent=2, ensure_ascii=False)
            
            logger.info(f"✅ Cookies saved to {CONFIG['OUTPUT_FILE']}")

            # Netscape ফরম্যাটে সেভ
            save_cookies_as_netscape(all_cookies)

            # সারাংশ প্রিন্ট
            print("\n" + "="*60)
            print("📋 COOKIE SUMMARY")
            print("="*60)
            
            edge_cookie = cookie_data['summary']['edge_cache_cookie']
            if edge_cookie:
                print(f"🔑 Edge-Cache Cookie Found!")
                print(f"   Name: {edge_cookie['name']}")
                print(f"   Value: {edge_cookie['value'][:80]}...")
                print(f"   Expires: {edge_cookie.get('expires', 'Session')}")
                print(f"   Expiry Check: {check_cookie_expiry(edge_cookie)}")
            
            print(f"\n📊 Statistics:")
            print(f"   Total Cookies: {len(all_cookies)}")
            print(f"   Important: {len(important_cookies)}")
            print("="*60)

            return cookie_data

        except Exception as e:
            logger.error(f"❌ Error: {str(e)}")
            import traceback
            traceback.print_exc()
            return None
        finally:
            await browser.close()

# ==================== HTTP REQUEST WITH COOKIES ====================
def use_cookies_for_request(url: str, method: str = "GET", headers: dict = None):
    """
    সংগৃহীত Cookie ব্যবহার করে HTTP রিকোয়েস্ট পাঠায়
    """
    try:
        import requests
    except ImportError:
        logger.error("❌ Requests not installed! Run: pip install requests")
        return None
    
    cookies = load_cookies_from_file()
    if not cookies:
        logger.error("❌ No cookies found. Run scraper first.")
        return None

    # Cookie ডিকশনারি তৈরি করুন
    cookie_dict = {c['name']: c['value'] for c in cookies}
    
    # HTTP সেশন তৈরি করুন
    session = requests.Session()
    session.cookies.update(cookie_dict)
    
    # Headers সেট করুন
    if headers is None:
        headers = {
            'User-Agent': CONFIG['USER_AGENT'],
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.9',
        }
    
    session.headers.update(headers)
    
    # রিকোয়েস্ট পাঠান
    try:
        logger.info(f"📡 Sending {method} request to: {url}")
        response = session.request(method, url, timeout=10)
        
        logger.info(f"✅ Status Code: {response.status_code}")
        logger.info(f"📊 Response Size: {len(response.content)} bytes")
        
        return response
    except Exception as e:
        logger.error(f"❌ Request failed: {str(e)}")
        return None

# ==================== MAIN FUNCTION ====================
def main():
    """মেইন ফাংশন - সবকিছু এখান থেকে শুরু"""
    print("="*60)
    print("🍪 TOFFEE TV COOKIE SCRAPER (All-in-One)")
    print("="*60)
    
    # কমান্ড লাইন আর্গুমেন্ট চেক
    if len(sys.argv) > 1:
        if sys.argv[1] == "--use-cookies":
            # Cookie ব্যবহার করে রিকোয়েস্ট পাঠান
            url = sys.argv[2] if len(sys.argv) > 2 else CONFIG['BASE_URL']
            response = use_cookies_for_request(url)
            if response:
                print(f"\n✅ Response Status: {response.status_code}")
                print(f"📄 First 500 chars of response:")
                print("-"*40)
                print(response.text[:500])
                print("-"*40)
            return
        
        elif sys.argv[1] == "--help" or sys.argv[1] == "-h":
            print("\n📖 Usage:")
            print("  python main.py                    # Run cookie scraper")
            print("  python main.py --use-cookies URL  # Use cookies to make request")
            print("  python main.py --help             # Show this help")
            return
    
    # ডিফল্ট: স্ক্র্যাপার রান
    result = asyncio.run(scrape_toffee_cookies())
    
    if result:
        print("\n✅ Scraping completed successfully!")
        print(f"📁 Check '{CONFIG['OUTPUT_FILE']}' for details")
        print(f"📁 Check 'cookies.txt' for Netscape format")
        
        # অতিরিক্ত: Cookie দিয়ে টেস্ট রিকোয়েস্ট
        print("\n🔍 Testing cookies with a request...")
        response = use_cookies_for_request(CONFIG['BASE_URL'])
        if response and response.status_code == 200:
            print("✅ Cookies are working!")
        else:
            print("⚠️ Cookies might not be working properly")
    else:
        print("\n❌ Scraping failed!")
        sys.exit(1)

# ==================== ENTRY POINT ====================
if __name__ == "__main__":
    main()
